name = "BioSequenceGraphs"
uuid = "3aa97884-90e5-11e8-2134-af657ec4f203"
authors = ["Ben J. Ward <benjward@protonmail.com>"]
version = "0.1.0"

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
